# Generated by Django 3.1.3 on 2020-12-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('movement', models.IntegerField()),
                ('weapon_skill', models.IntegerField()),
                ('ballistic_skill', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('wounds', models.IntegerField()),
                ('attacks', models.IntegerField()),
                ('leadership', models.IntegerField()),
                ('save', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=200)),
                ('w_range', models.IntegerField()),
                ('w_type', models.CharField(choices=[('RF', 'Rapid Fire'), ('H', 'Heavy'), ('A', 'Assault'), ('P', 'Pistol'), ('G', 'Grenade')], max_length=15)),
                ('w_shots', models.IntegerField()),
                ('w_strengh', models.IntegerField()),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs_parser.unitprofile')),
            ],
        ),
    ]
